name: jyusho_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
